import type { Release19SpecificationLockInput } from './3gpp-compliance.js';

const portal = (specificationId: number) =>
  `https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=${specificationId}`;

function deepFreeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    for (const child of Object.values(value)) deepFreeze(child);
    Object.freeze(value);
  }
  return value;
}

/**
 * Immutable Release 19 baseline verified against the official 3GPP portal on
 * 2026-07-26. Archive hashes cover the exact official ZIP bytes, not an
 * extracted or republished document.
 *
 * This lock does not promote any SignalLab profile. A new 3GPP revision,
 * changed clause, or changed publication digest is a revalidation event.
 */
export const RELEASE_19_SPECIFICATION_LOCK = deepFreeze({
  schemaVersion: 1,
  lockId: '3gpp-release-19-2026-07-26',
  release: 19,
  verifiedAsOf: '2026-07-26',
  versionPolicy: {
    selection: 'frozen-explicit-version',
    automaticallyTrackLatest: false,
    newerOrUnknownRevisionAction: 'require-revalidation-before-promotion',
  },
  specifications: [
    {
      referenceId: '3gpp-ts-45-002-r19-v19-0-0',
      technology: 'geran',
      specification: 'TS 45.002',
      title: 'GSM/EDGE Multiplexing and multiple access on the radio path',
      release: 19,
      version: '19.0.0',
      role: 'waveform-structure',
      clauses: [
        { clauseId: '4.3', title: 'Timeslots and TDMA frames', applicability: 'digital' },
        { clauseId: '5.2.3.1', title: 'Normal burst', applicability: 'digital' },
      ],
      portalUrl: portal(2706),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/45_series/45.002/45002-j00.zip',
        mediaType: 'application/zip',
        sha256: '84d7f48aea5c11d7c85a8fb273ebe46fc756c637224f136d6f9ab5ae44c4c62d',
      },
    },
    {
      referenceId: '3gpp-ts-45-003-r19-v19-0-0',
      technology: 'geran',
      specification: 'TS 45.003',
      title: 'GSM/EDGE Channel coding',
      release: 19,
      version: '19.0.0',
      role: 'channel-coding',
      clauses: [
        { clauseId: '3', title: 'General channel-coding definitions', applicability: 'digital' },
        { clauseId: '4', title: 'Coding, interleaving and mapping on logical channels', applicability: 'digital' },
      ],
      portalUrl: portal(2707),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/45_series/45.003/45003-j00.zip',
        mediaType: 'application/zip',
        sha256: '903afd8aa61b3bd121a70759f4e893d6264e888bdc06f7a3b9ed883bc935b6ab',
      },
    },
    {
      referenceId: '3gpp-ts-45-004-r19-v19-0-0',
      technology: 'geran',
      specification: 'TS 45.004',
      title: 'GSM/EDGE Modulation',
      release: 19,
      version: '19.0.0',
      role: 'waveform-structure',
      clauses: [
        { clauseId: '2', title: 'GMSK modulation', applicability: 'digital' },
        { clauseId: '2.1', title: 'GMSK modulating bit rate', applicability: 'digital' },
      ],
      portalUrl: portal(2708),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/45_series/45.004/45004-j00.zip',
        mediaType: 'application/zip',
        sha256: 'c056a4f210b279ec9cf36aa4ae33b86c6979ef7f2103ff723e8139ab9e0d8c09',
      },
    },
    {
      referenceId: '3gpp-ts-45-005-r19-v19-0-0',
      technology: 'geran',
      specification: 'TS 45.005',
      title: 'GSM/EDGE Radio transmission and reception',
      release: 19,
      version: '19.0.0',
      role: 'rf-requirements',
      clauses: [
        { clauseId: '4.2.1', title: 'Spectrum due to modulation and wide band noise', applicability: 'conducted-rf' },
        { clauseId: 'Annex A', title: 'Modulation-spectrum measurement filter', applicability: 'conducted-rf' },
      ],
      portalUrl: portal(2709),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/45_series/45.005/45005-j00.zip',
        mediaType: 'application/zip',
        sha256: '8a71fe9db2260aa2d5a5febcba19e77b7608989376e3fd75b28439ef225ced34',
      },
    },
    {
      referenceId: '3gpp-ts-36-104-r19-v19-2-0',
      technology: 'lte',
      specification: 'TS 36.104',
      title: 'E-UTRA Base Station radio transmission and reception',
      release: 19,
      version: '19.2.0',
      role: 'rf-requirements',
      clauses: [
        { clauseId: '5.6', title: 'Channel bandwidth', applicability: 'digital' },
        { clauseId: '6.5', title: 'Output power dynamics', applicability: 'conducted-rf' },
        { clauseId: '6.6', title: 'Output RF spectrum emissions', applicability: 'conducted-rf' },
      ],
      portalUrl: portal(2412),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/36_series/36.104/36104-j20.zip',
        mediaType: 'application/zip',
        sha256: 'e053f9ea42e4e4ff64244225e4fbbf81c7eddde661d8539f290696628df5d7d5',
      },
    },
    {
      referenceId: '3gpp-ts-36-141-r19-v19-1-0',
      technology: 'lte',
      specification: 'TS 36.141',
      title: 'E-UTRA Base Station conformance testing',
      release: 19,
      version: '19.1.0',
      role: 'conducted-conformance',
      clauses: [
        { clauseId: '6.1.1', title: 'E-UTRA test models', applicability: 'digital' },
        { clauseId: '6.1.1.1', title: 'E-TM 1.1', applicability: 'digital' },
        { clauseId: 'Table 6.1.1.1-1', title: 'E-TM 1.1 physical-channel allocation', applicability: 'digital' },
        { clauseId: '6.1.2', title: 'Data content of physical channels and signals for E-TM', applicability: 'digital' },
        { clauseId: '6.1.2.1', title: 'Reference signals', applicability: 'digital' },
        { clauseId: '6.1.2.2', title: 'Primary synchronization signal', applicability: 'digital' },
        { clauseId: '6.1.2.3', title: 'Secondary synchronization signal', applicability: 'digital' },
        { clauseId: '6.1.2.4', title: 'PBCH', applicability: 'digital' },
        { clauseId: '6.1.2.5', title: 'PCFICH', applicability: 'digital' },
        { clauseId: '6.1.2.6', title: 'PHICH', applicability: 'digital' },
        { clauseId: '6.1.2.7', title: 'PDCCH', applicability: 'digital' },
        { clauseId: '6.1.2.8', title: 'PDSCH or sPDSCH', applicability: 'digital' },
        { clauseId: '6.5', title: 'Transmitted signal quality', applicability: 'conducted-rf' },
        { clauseId: '6.6', title: 'Unwanted emissions', applicability: 'conducted-rf' },
      ],
      portalUrl: portal(2421),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/36_series/36.141/36141-j10.zip',
        mediaType: 'application/zip',
        sha256: '9b3b6eeff49b64892f6ffe3e306547495ac8d2ee2816dfeb7f3d4b2a036599cf',
      },
    },
    {
      referenceId: '3gpp-ts-36-211-r19-v19-3-0',
      technology: 'lte',
      specification: 'TS 36.211',
      title: 'E-UTRA Physical channels and modulation',
      release: 19,
      version: '19.3.0',
      role: 'waveform-structure',
      clauses: [
        { clauseId: '4', title: 'Frame structure', applicability: 'digital' },
        { clauseId: '4.1', title: 'Frame structure type 1 for FDD', applicability: 'digital' },
        { clauseId: '6', title: 'Downlink physical channels and modulation', applicability: 'digital' },
        { clauseId: '6.2.1', title: 'Resource grid', applicability: 'digital' },
        { clauseId: '6.2.2', title: 'Resource elements', applicability: 'digital' },
        { clauseId: '6.2.3', title: 'Resource blocks', applicability: 'digital' },
        { clauseId: '6.2.4', title: 'Resource-element groups', applicability: 'digital' },
        { clauseId: '6.3', title: 'Physical downlink shared channel', applicability: 'digital' },
        { clauseId: '6.3.1', title: 'PDSCH scrambling', applicability: 'digital' },
        { clauseId: '6.3.2', title: 'PDSCH modulation', applicability: 'digital' },
        { clauseId: '6.3.3.1', title: 'Single-antenna-port layer mapping', applicability: 'digital' },
        { clauseId: '6.3.4.1', title: 'Single-antenna-port identity precoding', applicability: 'digital' },
        { clauseId: '6.3.5', title: 'PDSCH mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.4', title: 'Physical downlink shared channel', applicability: 'digital' },
        { clauseId: '6.6.1', title: 'PBCH scrambling', applicability: 'digital' },
        { clauseId: '6.6.2', title: 'PBCH modulation', applicability: 'digital' },
        { clauseId: '6.6.3', title: 'PBCH layer mapping and precoding', applicability: 'digital' },
        { clauseId: '6.6.4', title: 'PBCH mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.7', title: 'Physical control format indicator channel', applicability: 'digital' },
        { clauseId: '6.7.1', title: 'PCFICH scrambling', applicability: 'digital' },
        { clauseId: '6.7.2', title: 'PCFICH modulation', applicability: 'digital' },
        { clauseId: '6.7.3', title: 'PCFICH layer mapping and precoding', applicability: 'digital' },
        { clauseId: '6.7.4', title: 'PCFICH mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.8', title: 'Physical downlink control channel', applicability: 'digital' },
        { clauseId: '6.8.1', title: 'PDCCH formats', applicability: 'digital' },
        { clauseId: '6.8.2', title: 'PDCCH multiplexing and scrambling', applicability: 'digital' },
        { clauseId: '6.8.3', title: 'PDCCH modulation', applicability: 'digital' },
        { clauseId: '6.8.4', title: 'PDCCH layer mapping and precoding', applicability: 'digital' },
        { clauseId: '6.8.5', title: 'PDCCH mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.9', title: 'Physical hybrid ARQ indicator channel', applicability: 'digital' },
        { clauseId: '6.9.1', title: 'PHICH modulation', applicability: 'digital' },
        { clauseId: '6.9.2', title: 'PHICH resource group alignment, layer mapping and precoding', applicability: 'digital' },
        { clauseId: '6.9.3', title: 'PHICH mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.10.1', title: 'Cell-specific reference signal', applicability: 'digital' },
        { clauseId: '6.10.1.1', title: 'Cell-specific reference-signal sequence generation', applicability: 'digital' },
        { clauseId: '6.10.1.2', title: 'Cell-specific reference-signal mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.11', title: 'Synchronization signals and physical-cell identity decomposition', applicability: 'digital' },
        { clauseId: '6.11.1', title: 'Primary synchronization signal', applicability: 'digital' },
        { clauseId: '6.11.1.1', title: 'PSS sequence generation', applicability: 'digital' },
        { clauseId: '6.11.1.2', title: 'PSS mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.11.2', title: 'Secondary synchronization signal', applicability: 'digital' },
        { clauseId: '6.11.2.1', title: 'SSS sequence generation', applicability: 'digital' },
        { clauseId: '6.11.2.2', title: 'SSS mapping to resource elements', applicability: 'digital' },
        { clauseId: '6.12', title: 'OFDM baseband signal generation', applicability: 'digital' },
        { clauseId: '7.1.1', title: 'BPSK modulation', applicability: 'digital' },
        { clauseId: '7.1.2', title: 'QPSK modulation', applicability: 'digital' },
        { clauseId: '7.2', title: 'Pseudo-random sequence generation', applicability: 'digital' },
      ],
      portalUrl: portal(2425),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/36_series/36.211/36211-j30.zip',
        mediaType: 'application/zip',
        sha256: 'c1b132375361596e713dc51bfa20afbe4bf4c92bf1992c829a775f59a2ece5a1',
      },
    },
    {
      referenceId: '3gpp-ts-36-212-r19-v19-3-0',
      technology: 'lte',
      specification: 'TS 36.212',
      title: 'E-UTRA Multiplexing and channel coding',
      release: 19,
      version: '19.3.0',
      role: 'channel-coding',
      clauses: [
        { clauseId: '4', title: 'Mapping to physical channels', applicability: 'digital' },
        { clauseId: '5.1.4.2.1', title: 'Sub-block interleaver used by PDCCH REG-quadruplet permutation', applicability: 'digital' },
        { clauseId: '5.3', title: 'Downlink transport channels and control information', applicability: 'digital' },
        { clauseId: '5.3.4', title: 'Control format indicator', applicability: 'digital' },
        { clauseId: '5.3.4.1', title: 'Control format indicator channel coding', applicability: 'digital' },
        { clauseId: '5.3.5', title: 'HARQ indicator', applicability: 'digital' },
        { clauseId: '5.3.5.1', title: 'HARQ indicator channel coding', applicability: 'digital' },
      ],
      portalUrl: portal(2426),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/36_series/36.212/36212-j30.zip',
        mediaType: 'application/zip',
        sha256: '06a40a3b3214d372b0a6008ee1c885cd025ed30aef6399c9ea76a1d4593a1450',
      },
    },
    {
      referenceId: '3gpp-ts-36-213-r19-v19-4-0',
      technology: 'lte',
      specification: 'TS 36.213',
      title: 'E-UTRA Physical layer procedures',
      release: 19,
      version: '19.4.0',
      role: 'physical-procedures',
      clauses: [
        { clauseId: '7', title: 'Physical downlink shared channel related procedures', applicability: 'digital' },
      ],
      portalUrl: portal(2427),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/36_series/36.213/36213-j40.zip',
        mediaType: 'application/zip',
        sha256: 'ba17b66cd85bca243592bd1702f68647728e66036e7524ef05676aa8dffc4702',
      },
    },
    {
      referenceId: '3gpp-ts-38-104-r19-v19-5-0',
      technology: 'nr',
      specification: 'TS 38.104',
      title: 'NR Base Station radio transmission and reception',
      release: 19,
      version: '19.5.0',
      role: 'rf-requirements',
      clauses: [
        { clauseId: '6.5', title: 'Output power dynamics', applicability: 'conducted-rf' },
        { clauseId: '6.6', title: 'Output RF spectrum emissions', applicability: 'conducted-rf' },
      ],
      portalUrl: portal(3202),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/38_series/38.104/38104-j50.zip',
        mediaType: 'application/zip',
        sha256: '66c28dbb5944e7a2fb53d708d43f00195fb5d5f291422b4b3a2b4e84ffd9e18a',
      },
    },
    {
      referenceId: '3gpp-ts-38-141-1-r19-v19-5-0',
      technology: 'nr',
      specification: 'TS 38.141-1',
      title: 'NR Base Station conformance testing Part 1: Conducted conformance testing',
      release: 19,
      version: '19.5.0',
      role: 'conducted-conformance',
      clauses: [
        { clauseId: '4.9.2.2.1', title: 'NR-FR1-TM1.1', applicability: 'digital' },
        { clauseId: '4.9.2.2.5', title: 'NR-FR1-TM3.1', applicability: 'digital' },
        { clauseId: '4.9.2.2.6', title: 'NR-FR1-TM3.1a', applicability: 'digital' },
        { clauseId: '4.9.2.2.6A', title: 'NR-FR1-TM3.1b', applicability: 'digital' },
        { clauseId: '6', title: 'Transmitter characteristics', applicability: 'conducted-rf' },
      ],
      portalUrl: portal(3367),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/38_series/38.141-1/38141-1-j50.zip',
        mediaType: 'application/zip',
        sha256: '4f732b675e2273ff932fe41519b52d9b5d3af6f74d49fc4520bf813bad4e3d31',
      },
    },
    {
      referenceId: '3gpp-ts-38-141-2-r19-v19-5-0',
      technology: 'nr',
      specification: 'TS 38.141-2',
      title: 'NR Base Station conformance testing Part 2: Radiated conformance testing',
      release: 19,
      version: '19.5.0',
      role: 'radiated-conformance',
      clauses: [
        { clauseId: '6', title: 'Radiated transmitter characteristics', applicability: 'radiated-ota' },
      ],
      portalUrl: portal(3368),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/38_series/38.141-2/38141-2-j50.zip',
        mediaType: 'application/zip',
        sha256: '7716103158ce6602157a041766573ea8dd34d2dc002d615ab0b88ff7f2ffdc0d',
      },
    },
    {
      referenceId: '3gpp-ts-38-211-r19-v19-4-0',
      technology: 'nr',
      specification: 'TS 38.211',
      title: 'NR Physical channels and modulation',
      release: 19,
      version: '19.4.0',
      role: 'waveform-structure',
      clauses: [
        { clauseId: '4.2', title: 'Numerologies', applicability: 'digital' },
        { clauseId: '4.3', title: 'Frame structure', applicability: 'digital' },
        { clauseId: '4.4', title: 'Resource grids', applicability: 'digital' },
        { clauseId: '5', title: 'Generic physical-layer procedures', applicability: 'digital' },
        { clauseId: '7', title: 'Downlink physical channels and signals', applicability: 'digital' },
      ],
      portalUrl: portal(3213),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/38_series/38.211/38211-j40.zip',
        mediaType: 'application/zip',
        sha256: 'd1591bb71f3e82a65cc40847a0aaed7d5de8bf376b2f178e10a19741c550db4f',
      },
    },
    {
      referenceId: '3gpp-ts-38-212-r19-v19-4-0',
      technology: 'nr',
      specification: 'TS 38.212',
      title: 'NR Multiplexing and channel coding',
      release: 19,
      version: '19.4.0',
      role: 'channel-coding',
      clauses: [
        { clauseId: '5', title: 'Downlink transport channels and control information', applicability: 'digital' },
      ],
      portalUrl: portal(3214),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/38_series/38.212/38212-j40.zip',
        mediaType: 'application/zip',
        sha256: 'e3ee2ed97a38317ad1457ab27e3ab28dabc49fe4a92dbb6d3813a86254d6ef90',
      },
    },
    {
      referenceId: '3gpp-ts-38-213-r19-v19-4-0',
      technology: 'nr',
      specification: 'TS 38.213',
      title: 'NR Physical layer procedures for control',
      release: 19,
      version: '19.4.0',
      role: 'physical-procedures',
      clauses: [
        { clauseId: '10', title: 'UE procedures for receiving control information', applicability: 'digital' },
      ],
      portalUrl: portal(3215),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/38_series/38.213/38213-j40.zip',
        mediaType: 'application/zip',
        sha256: '3d912f46095558119bac37bf9e775ea52132e92a51f95fd472ed5fc7e9766322',
      },
    },
    {
      referenceId: '3gpp-ts-38-214-r19-v19-4-0',
      technology: 'nr',
      specification: 'TS 38.214',
      title: 'NR Physical layer procedures for data',
      release: 19,
      version: '19.4.0',
      role: 'physical-procedures',
      clauses: [
        { clauseId: '5', title: 'Physical downlink shared channel related procedures', applicability: 'digital' },
      ],
      portalUrl: portal(3216),
      publication: {
        publisher: '3GPP',
        url: 'https://www.3gpp.org/ftp/Specs/archive/38_series/38.214/38214-j40.zip',
        mediaType: 'application/zip',
        sha256: '73772f5579d59065ff0e6e3b6e86a2439707ba86013e0b6413535db5e471c012',
      },
    },
  ],
  profileAdmissions: ([
    ['gsm-900-loaded-bcch', 'geran'],
    ['gsm-normal-burst', 'geran'],
    ['gsm-qpsk-higher-symbol-rate-burst', 'geran'],
    ['gsm-aqpsk-normal-burst', 'geran'],
    ['gsm-8psk-normal-burst', 'geran'],
    ['gsm-16qam-higher-symbol-rate-burst', 'geran'],
    ['gsm-32qam-higher-symbol-rate-burst', 'geran'],
    ['lte-band3-fdd-20m', 'lte'],
    ['lte-band38-tdd-10m', 'lte'],
    ['lte-etm1.1', 'lte'],
    ['lte-etm3.1', 'lte'],
    ['lte-etm3.1a', 'lte'],
    ['lte-etm3.1b', 'lte'],
    ['lte-ntm', 'lte'],
    ['lte-nbiot-guard-isolated-component', 'lte'],
    ['lte-nbiot-inband-isolated-component', 'lte'],
    ['lte-etm-1-1-10mhz-fdd', 'lte'],
    ['nr-n3-fdd-20m', 'nr'],
    ['nr-n78-tdd-100m', 'nr'],
    ['nr-fr1-tm1.1', 'nr'],
    ['nr-fr1-tm3.1', 'nr'],
    ['nr-fr1-tm3.1a', 'nr'],
    ['nr-fr1-tm3.1b', 'nr'],
    ['nr-nbiot-inband-isolated-component', 'nr'],
  ] as const).map(([profileId, technology]) => ({
    profileId,
    technology,
    status: 'unpromoted',
    currentClassification: 'standards-derived-engineering-projection',
    promotionEvidenceBundleId: null,
    reason: profileId === 'lte-etm-1-1-10mhz-fdd'
      ? 'The exact one-frame artifact and retained independent comparison exist, but the manifest remains reference-generated and no authenticated, executed clause campaign has promoted this profile.'
      : 'The current SignalLab cellular generator is an engineering projection without a complete standards-exact resource grid, protocol decode, independent oracle, or qualifying evidence bundle.',
  })),
} as const satisfies Release19SpecificationLockInput);
